[[parameters]]
obis_key = "identifier"
name = "Gerätetyp mit Software Version"

[[parameters]]
obis_key = "1-0:0.0.0*255"
name = "Eigentumsnummer"

[[parameters]]
obis_key = "1-0:96.1.0*255"
name = "Geräte-Identifikationsnummer"

[[parameters]]
obis_key = "0-0:96.1.255*255"
name = "Geräte-Identifikationsnummer"

[[parameters]]
obis_key = "1-0:1.8.0*255"
name = "Zählerstand Bezug (Tariflos)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:2.8.0*255"
name = "Zählerstand Lieferung (Tariflos)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:1.8.1*255"
name = "Zählerstand Bezug (Tarif 1)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:2.8.1*255"
name = "Zählerstand Lieferung (Tarif 1)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:1.8.2*255"
name = "Zählerstand Bezug (Tarif 2)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:2.8.2*255"
name = "Zählerstand Lieferung (Tarif 2)"
class = "energy"
state_class = "total"
uom = "kWh"
suggested_display_precision = 3
min_value = 0

[[parameters]]
obis_key = "1-0:16.7.0*255"
name = "Momentan-Leistungen"
class = "power"
state_class = "measurement"
uom = "W"
suggested_display_precision = 1
min_value = 0
max_value = 23000

[[parameters]]
obis_key = "1-0:36.7.0*255"
name = "Momentane Leistung L1"
class = "power"
state_class = "measurement"
uom = "W"
suggested_display_precision = 1
min_value = 0
max_value = 23000

[[parameters]]
obis_key = "1-0:56.7.0*255"
name = "Momentane Leistung L2"
class = "power"
state_class = "measurement"
uom = "W"
suggested_display_precision = 1
min_value = 0
max_value = 23000

[[parameters]]
obis_key = "1-0:76.7.0*255"
name = "Momentane Leistung L3"
class = "power"
state_class = "measurement"
uom = "W"
suggested_display_precision = 1
min_value = 0
max_value = 23000

[[parameters]]
obis_key = "1-0:32.7.0*255"
name = "Spannung L1"
class = "voltage"
state_class = "measurement"
uom = "V"
suggested_display_precision = 1
min_value = 200
max_value = 260

[[parameters]]
obis_key = "1-0:52.7.0*255"
name = "Spannung L2"
class = "voltage"
state_class = "measurement"
uom = "V"
suggested_display_precision = 1
min_value = 200
max_value = 260

[[parameters]]
obis_key = "1-0:72.7.0*255"
name = "Spannung L3"
class = "voltage"
state_class = "measurement"
uom = "V"
suggested_display_precision = 1
min_value = 200
max_value = 260

[[parameters]]
obis_key = "1-0:96.5.0*255"
name = "Betriebszustand"

[[parameters]]
obis_key = "0-0:96.8.0*255"
name = "Betriebsdauer"
uom = "sec."

[[parameters]]
obis_key = "1-0:1.7.0*255"
name = "Momentan-Leistungen"
class = "power"
state_class = "measurement"
uom = "W"
suggested_display_precision = 1
min_value = 0
max_value = 23000

[[parameters]]
obis_key = "1-0:21.7.0*255"
name = "Wirkleistung L1 Bezug (Momentan)"
class = "power"
state_class = "measurement"
uom = "W"

[[parameters]]
obis_key = "1-0:41.7.0*255"
name = "Wirkleistung L2 Bezug (Momentan)"
class = "power"
state_class = "measurement"
uom = "W"

[[parameters]]
obis_key = "1-0:61.7.0*255"
name = "Wirkleistung L3 Bezug (Momentan)"
class = "power"
state_class = "measurement"
uom = "W"

[[parameters]]
obis_key = "1-0:96.5.5*255"
name = "Status"


